---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - 'org.apache.activemq.artemis:*'
  - 'java.lang:*'
rules:
- pattern: "^org.apache.activemq.artemis<.*>MessageCount:"
- pattern: "^org.apache.activemq.artemis<.*>MessagesAcknowledged:"
- pattern: "^org.apache.activemq.artemis<.*>ConsumerCount:"
- pattern: "^org.apache.activemq.artemis<.*>TotalMessageCount:"
- pattern: "^org.apache.activemq.artemis<.*>TotalMessagesAcknowledged:"
- pattern: "^org.apache.activemq.artemis<.*>TotalConsumerCount:"
- pattern: "^org.apache.activemq.artemis<.*>ConnectionCount:"
- pattern: "^org.apache.activemq.artemis<.*>AddressSize:"
- pattern: "^org.apache.activemq.artemis<.*>NumberOfPages:"
- pattern: "^java.lang<.*>ProcessCpuLoad:"
- pattern: "^java.lang<.*>ProcessCpuTime:"
